
from typing import Optional, Tuple, Iterable, Union, List
import array 

class Solver:
    def __init__(self, /, time_limit: int = ..., confl_limit: int = ..., verbose: int = ...): ...
    def add_clauses(self, clauses: Union[List[int], array.array]) -> None: ...
    def nb_vars(self) -> int: ...
    def assignment(self, vars: Iterable[int]) -> Tuple[Optional[bool], ...]: ...
    def solve(self, assumptions: Iterable[int] = ..., verbose: int = ..., time_limit: float = ..., confl_limit: int = ..., model: bool = ...) -> Tuple[Optional[bool], Optional[Tuple[Optional[bool], ...]]]: ...